{
    "name": "TRIDENTE",
    "version": "1.10",
    "depends": ['base','crm'],
    "author": "Lider IT",
    "category": "Sales",
    "description": """	Modulo General Gestion  TRIDENTE """,
    "website":'http://www.liderit.es',
   
    "init_xml": [],
    'update_xml': [
                'security/ir.model.access.csv',
                'security/groups.xml',  
                'data/inicial_data.xml',    
                'views/res_partner_view.xml',
                'views/oppor_from_view.xml',
                'views/ferias_view.xml',
                'views/productos_crm_view.xml',
                'views/product_view.xml',
                'views/project_view.xml',
#                 'views/event_registrations_ferias_view.xml',
                'views/parameters_view.xml',
                'views/menu.xml',
                   ],
#     'data': ['workflow/workflow.xml'],
    'demo_xml': [],
#     'data': ['general_data.xml'],
    'installable': True,
	'active': False,
}   
