{
    "name": "style_aristos",
    "version": "1.11",
    # en depends comentadas para que actualice mas rapido, descomentar en produccion
    "depends": [
      'base',
      # 'sale_commission_liderit',
      'sale_commission',
      # 'account',
      # 'purchase',
      # 'stock',
      'base_partner_sequence',
      'partner_search_by_ref',
      'product_multi_image',
      'product_search_supplier_code',
      'stock_move_sale_line',
      'sale_sourced_by_line',
      'sale_order_type',
      # # 'sale_exceptions_groups',
      # 'liderit_partner_alta',
      # 'partner_paydays',
      'liderit_product_variant_defaultcode',
      'liderit_global_discount',
      # 'liderit_account_invoice_split',
      # 'mrp_repair',
      # 'account_chart_update',
      # 'l10n_es_dua',
      'sale_order_invisible_for_customer',
      'stock_reserve',
      'stock_reserve_sale_liderit',
      # 'sale_stock',
      # 'web_translate_dialog',
      'liderit_invoice_partner_bank_usability',
      # 'account_payment_min_invoice_date',
      # 'account_payment_min_residual',
      # 'account_payment_term_initial_postpone',
      # 'account_invoice_change_due',
      # 'account_invoice_export_data',
      # 'product_m2mcategories',
      'account_payment_sale',
      'odoo_multi_channel_sale',
      'account_due_list',
      'account_link_order_lines'
       ],
        

    "author": "Lider IT",
    "category": "Sales",
    "description": """	Gestion Style Aristos   """,
    "website":'http://www.liderit.es',
   
    "init_xml": [],
    'data': [
                    'security/ir.model.access.csv',
                    'security/groups.xml',
                    'views/account_invoice.xml',
                    'views/settlement_view.xml',
                    'views/product_view.xml',
                    'views/res_partner_view.xml',
                    'views/type_of_material_view.xml',                   
                    'views/parameters_view.xml',
                    'views/payment_term_view.xml',
                    'views/purchase_view.xml',
                    'views/colection_view.xml',
                    'views/sale_view.xml',
                    'wizard_desactivate/product_desactivate_view.xml',
                    'wizard_desactivate/product_get_image_view.xml',
                    'views/menu.xml',
                   ],
#     'data': ['workflow/workflow.xml'],
    'demo_xml': [],
#     'data': ['general_data.xml'],
    'installable': True,
	'active': False,
}   
